export const API_BASE_URL = 'http://localhost:8081/api';

export const API_ENDPOINTS = {
  AUTH_LOGIN: `${API_BASE_URL}/auth/login`,
  AUTH_FORGOT_PASSWORD: `${API_BASE_URL}/auth/forgot-password`,
  AUTH_RESET_PASSWORD: `${API_BASE_URL}/auth/reset-password`,
  ADMIN_RH: `${API_BASE_URL}/admin/rh`,
  ADMIN_PROFILE: `${API_BASE_URL}/admin/profile`,
  ADMIN_PROFILE_PHOTO: `${API_BASE_URL}/admin/profile/photo`,
  EMPLOYES: `${API_BASE_URL}/employes`,
  EMPLOYE_PROFILE: `${API_BASE_URL}/employes/profile`,
  EMPLOYE_PROFILE_PHOTO: `${API_BASE_URL}/employes/profile/photo`,
  EMPLOYE_CHANGE_PASSWORD: `${API_BASE_URL}/employes/change-password`,
  RESPONSABLES_RH: `${API_BASE_URL}/responsables-rh`,
  RH_PROFILE: `${API_BASE_URL}/responsables-rh/profile`,
  RH_PROFILE_PHOTO: `${API_BASE_URL}/responsables-rh/profile/photo`,
  RH_CHANGE_PASSWORD: `${API_BASE_URL}/responsables-rh/change-password`,
  EXTERNAL_COMPANIES: `${API_BASE_URL}/external-companies`,
  EXTERNAL_PROFILE: `${API_BASE_URL}/external-companies/profile`,
  EXTERNAL_PROFILE_PHOTO: `${API_BASE_URL}/external-companies/profile/photo`,
  EXTERNAL_CHANGE_PASSWORD: `${API_BASE_URL}/external-companies/change-password`,
  EVENTS: `${API_BASE_URL}/events`,
  ACTIVITIES: `${API_BASE_URL}/activities`,
  FEEDBACKS: `${API_BASE_URL}/feedbacks`,
  IMAGES: `${API_BASE_URL}/images`,
  PARTICIPATIONS: `${API_BASE_URL}/participations`,
  PENDING_ACCOUNTS: `${API_BASE_URL}/pending-accounts`,
  DASHBOARD_STATS: `${API_BASE_URL}/dashboard/stats`,
};
