export enum EventStatus {
  PLANNED='PLANNED',
  ONGOING='ONGOING',
  COMPLETED='COMPLETED',
  CANCELLED='CANCELLED'
}
export enum ActivityStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED'
}
export const HTTP_STATUS = {
  OK:200,
  CREATED:201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500
};

