server:
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 26280231
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: eventteam.notifications@gmail.com
    password: yjhyelgzbecgmoxy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend:
    url: http://localhost:4200
  admin:
    email: admin@eventteam.com
    password: Admin@123
    name: Super Admin